OffchainLabs/nitro-contracts

src/osp/IOneStepProver.sol, src/osp/OneStepProverHostIo.sol, src/osp/OneStepProverMemory.sol, src/rollup/Config.sol, src/rollup/IRollupAdmin.sol, src/rollup/IRollupCore.sol, src/rollup/IRollupLogic.sol, src/rollup/Node.sol, src/rollup/RollupAdminLogic.sol, src/rollup/RollupCore.sol, src/rollup/RollupCreator.sol, src/rollup/RollupLib.sol, src/rollup/RollupProxy.sol, src/rollup/RollupUserLogic.sol, src/rollup/ValidatorUtils.sol, src/state/Deserialize.sol, src/state/Module.sol, src/state/ModuleMemory.sol, src/state/ModuleMemoryCompact.sol, test/contract/arbRollup.spec.ts, test/contract/common/rolluplib.ts
This PR resolved the 2 cyclic dependencies in `state` and `rollup` respectively
A quick check to verify there are no cyclic dependencies is to run:
```
yarn hardhat flatten src/rollup/RollupCreator.sol
yarn hardhat flatten src/state/MerkleProof.sol
```
hardhat will throw if there is circular import
```
Error HH603: Hardhat flatten doesn't support cyclic dependencies.
```
=> fix: resolve cyclic dependencies

src/bridge/ISequencerInbox.sol
The external view function stubs are missing from the ISequencerInbox interface for
- maxTimeVariation
- dasKeySetInfo
In solidity, public struct [autogenerate](https://docs.soliditylang.org/en/v0.8.20/contracts.html#visibility-and-getters) public views returning the struct members in order (excluding arrays and mappings). In the case of dasKeySetInfo which is a mapping, the view takes a key parameter of the same type as the mapping.
This PR adds the missing stubs.
=> chore(ISequencerInbox): Add Missing views

src/bridge/SequencerInbox.sol
This is more accurate as it doesn't charge the fixed costs against the L1 basefee.
=> Track L1 gas separately from basefee in batch posting report

src/mocks/Simple.sol
These checks catch a bug in retryable gas estimation but should always pass.
=> Add additional redeem checks to mock Simple.sol

src/bridge/SequencerInbox.sol
This field is used exclusively for log lookups, so if the SequencerInbox is deployed on an L2 it should use the L2 block number.
=> Use L2 block number for keyset info if applicable

src/precompiles/ArbOwner.sol, src/precompiles/ArbOwnerPublic.sol
Part of https://github.com/OffchainLabs/nitro/pull/1865
=> Add functions to read and write brotli compression level for fast compression

src/bridge/ERC20Bridge.sol, src/bridge/IERC20Bridge.sol, src/libraries/Error.sol, test/foundry/ERC20Bridge.t.sol
When withdraw-and-call is used in ERC20 based chains, it is important to make sure that extra call cannot be used to move escrowed native token in any way. We enforce it by doing native token balance check for bridge before/after the extra call is executed.
=> Add ERC20Bridge balance check

scripts/rollupCreation.ts, src/rollup/RollupCreator.sol, test/contract/arbRollup.spec.ts, test/foundry/RollupCreator.t.sol
All the input parameters for 'createRollup' entrypoint should be included in rollup's salt.
To make this more convenient input parameters are packed into 'RollupDeploymentParams' struct which looks like this:
struct RollupDeploymentParams {
Config config;
address batchPoster;
address[] validators;
uint256 maxDataSize;
address nativeToken;
bool deployFactoriesToL2;
uint256 maxFeePerGasForRetryables;
}
=> Update salt used for creating new rollups 

src/bridge/AbsOutbox.sol, src/bridge/IOutbox.sol, src/libraries/Error.sol, src/test-helpers/OutboxWithoutOptTester.sol
Outbox L2ToL1Context struct is changed from
```solidity
struct L2ToL1Context {
uint128 l2Block; // slot 1
uint128 l1Block; 
uint128 timestamp; // slot 2
bytes32 outputId; // slot 3
address sender; // slot 4
} 
```
to
```solidity
struct L2ToL1Context {
uint128 l2Block; // slot 1
uint128 timestamp;
bytes32 outputId; // slot 2
address sender; // slot 3
uint96 l1Block;
uint256 withdrawalAmount; // slot 4
}
```
This PR add `postUpgradeInit` to Outbox which is supposed to be called with upgradeAndCall to fix the default context.
=> feat: outbox postUpgradeInit

src/bridge/AbsBridge.sol, src/bridge/AbsOutbox.sol, src/bridge/IBridge.sol, src/bridge/IOutbox.sol, src/bridge/ISequencerInbox.sol, src/bridge/SequencerInbox.sol, src/libraries/Error.sol, src/mocks/BridgeStub.sol, src/rollup/AbsRollupEventInbox.sol, src/rollup/IRollupEventInbox.sol, src/rollup/RollupUserLogic.sol, src/test-helpers/BridgeTester.sol, src/test-helpers/OutboxWithoutOptTester.sol, test/contract/arbRollup.spec.ts
This PR included 2 changes that should only affect privileged methods
Superseding
* https://github.com/OffchainLabs/nitro-contracts/pull/54
* https://github.com/OffchainLabs/nitro-contracts/pull/48
=> feat: allow rollup update

LICENSE
Updates the BSL change date to 2028, ensuring that the 4 year delay is not cut short.
=> 2028 change date

src/osp/OneStepProverHostIo.sol
This adds a new type of preimage proof for Ethereum versioned hashes using the new EIP-4844 point evaluation precompile which will be introduced in Cancun along with blobs themselves. It's fine to deploy this before then though, because it'll just revert with "KZG_PRECOMPILE_MISSING" if the new preimage type is attempted to be proven before it's ready (and these preimages shouldn't even be attempted to be proven until 4844 is being utilized anyways).
This PR also requires that the WAVM ReadPreImage opcode be called with a preimage offset that's a multiple of 32, which was already what was done in practice before this.
=> Add WAVM KZG preimage proof

src/bridge/SequencerInbox.sol, test/contract/sequencerInbox.spec.4844.ts, test/foundry/SequencerInbox.t.sol
Instead of adding a new field for the blob basefee, this PR adds the blob cost into the existing extraGas field.
The main disadvantage of this PR is that ArbOS will think that the sequencer paid for the blob hash list data as tx data, but I think that should be a small error.
=> Include blob cost in extraGas field of batch posting reports

yul/Reader4844.yul
Specifically, the contract will now revert if passed callvalue or supplied an unknown selector.
=> Add safety checks to Reader4844.yul

src/bridge/ISequencerInbox.sol, src/bridge/SequencerInbox.sol, test/contract/sequencerInbox.spec.4844.ts, test/contract/toolkit4844.ts
This leaves other possibilities open for the DATA_AUTHENTICATED_FLAG.
Also renames `addSequencerL2BatchFromBlob` to `addSequencerL2BatchFromBlobs` (plural) since it can use multiple blobs.
=> Use 0x50 as the header byte for 4844 batches

src/bridge/SequencerInbox.sol
Points into https://github.com/OffchainLabs/nitro-contracts/pull/109
During gas estimation, the basefee could be zero. Instead of panicking, we just use a blob gas of 0.
=> Support zero basefee for gas estimation

package.json, yarn.lock
This PR remove sol2uml dependency, which is no longer used as we replaced it with foundry storage inspection.
sol2uml create dependency on python and chromium during yarn install, while it is already an optional dependencies ignore optional is not by default + npm/yarn --ignore-optional is so [broken](https://github.com/npm/cli/issues/4828) that it is not useable in many versions.
=> chore: remove sol2uml

src/bridge/AbsInbox.sol, src/bridge/IInboxBase.sol, src/bridge/ISequencerInbox.sol, src/bridge/SequencerInbox.sol, test/foundry/AbsInbox.t.sol
This PR
- This is a breaking change but should be fine because as of now only an EOA can call this method, so we are not going to run into issue like breaking an immutable contract. Alternatively, we can have this entrypoint call into the non-origin entrypoint but may require changes in the nitro node to locate the data properly.
SequencerInbox `fromOrigin` entrypoints are not removed yet, it will be fixed before EIP-3074 ship and when we have more clarity on its implementation. Since those entrypoints are only callable by the sequencer it pose less risk than the permissionless `sendL2MessageFromOrigin` and hence not removed in this PR for now.
=> fix: 3074 support

src/challenge/ChallengeLib.sol, src/challenge/ChallengeManager.sol, src/osp/IOneStepProofEntry.sol, src/osp/OneStepProofEntry.sol, test/signatures/OneStepProofEntry, test/signatures/test-sigs.bash
This PR move `getStartMachineHash` and `getEndMachineHash` from `ChallengeLib` to `OneStepProofEntry`, this change would make the `ChallengeManager` not compatible with previously deployed OSP.
=> refactor: move machine hash logic to osp

.github/workflows/contract-tests.yml
Using solution from https://github.com/orgs/community/discussions/26325#discussioncomment-5397362
Testing push hook here: https://github.com/OffchainLabs/nitro-contracts/commit/8bec0e5fbd70c7006e41ef7df0765f20f2520d33
=> ci: use sha instead of head ref to support push and pull

src/express-lane-auction/Burner.sol, src/express-lane-auction/Errors.sol, test/foundry/ExpressLaneAuction.t.sol, test/foundry/ExpressLaneBurner.t.sol
Simple burner contract to receive tokens for burning them
=> Express lane auction burn

src/precompiles/ArbWasm.sol
Corresponding nitro PR- https://github.com/OffchainLabs/nitro/pull/2640
Part of NIT-2771
=> Fix ArbWASM precompile minInitGas() method return types

src/precompiles/ArbWasm.sol
Reverts OffchainLabs/nitro-contracts#246
This breaks consensus as it would take effect retroactively
=> Revert "Fix ArbWASM precompile minInitGas() method return types"

foundry.toml, hardhat.config.ts, src/mocks/CreateTest.sol, src/mocks/HostioTest.sol
These contracts will be used by the nitro tests that check the equivalence between stylus and EVM.
Related Nitro PR: https://github.com/OffchainLabs/nitro/pull/2708
=> [NIT-2798] Add contracts for HostIO gas tests

deploy/ExpressLaneAuction.js
1. checkout nitro-contract branch express-lane-auction-deploy
2. edit deploy/ExpressLaneAuction.js for the required config
3. edit hardhat.config.ts to add your network e.g.
```
devnet: {
url: 'http://127.0.0.1:8547',
accounts: process.env['DEVNET_PRIVKEY']
? [process.env['DEVNET_PRIVKEY']]
: [],
},
```
5. run this to deploy
```
DEVNET_PRIVKEY=0x1234 yarn hardhat deploy --tags ExpressLaneAuction --write true --network devnet
```
=> chore: express lane deploy

scripts/files/configs/local.ts, scripts/files/configs/sepolia.ts
If `isDelayBufferable` is set to false, it is hard to re-enable without doing contract upgrade due to the flag is stored in an immutable for gas optimization. We temporarily disable delay buffer by using a large threshold value so that `isSynced` return true and will not require a delay proof when posting batches.
```
function isSynced(
BufferData storage self
) internal view returns (bool) {
return block.number - self.prevBlockNumber <= self.threshold;
}
```
the previous config for sepolia is not large enough because `prevBlockNumber` might be 0 after an upgrade
=> chore: effectively disableing delay buffer

test/foundry/ExpressLaneBalance.t.sol
Test might fail if `initialBalance==0 and reduceAmount==0` before the fix.
=> fix: express lane testReduce

audit-ci.jsonc, hardhat.config.ts, src/mocks/ArbOS11To32UpgradeTest.sol
Resolves NIT-2975
Adds a test contract that has a function that uses mcopy, an instruction that is supported in ArbOS 32 but not in ArbOS 11.
It also updates audit-ci.jsonc, with changes that are already in the develop branch.
To be used in https://github.com/OffchainLabs/nitro/pull/2837
Attention to the base branch.
Current version of develop is not compatible with nitro, so a `pre-bold` branch, checked out from main, was created to support changes that should be introduced to nitro while bold is not fully integrated to it.
=> ArbOS11To32UpgradeTest

src/mocks/BigMap.sol
This contracts makes it easy to add a bunch of storage slots in a single transation, and then in a separate transaction to free a bunch of those slots and add some others.
The idea is that this sort of operation will pass with the deterministic flag on the storage db implementation set and fail when it is not set.
Part of NIT-3068
=> Add a BigMap contract for testing the storage trie

src/precompiles/ArbOwner.sol
This was already reviewed for the `develop` branch, and the `yarn format` command was used to format it consistently with the rules on this branch.
=> Add setWasmMaxSize to ArbOwner in v2-main
