OffchainLabs/nitro-contracts

- src/bridge/Inbox.sol
This is a copy of https://github.com/OffchainLabs/nitro/pull/1495 from the old repo
> Fix ABI encoding in sendWithdrawEthToFork

- src/precompiles/ArbOwner.sol
- src/rollup/IRollupEventInbox.sol
- src/rollup/RollupAdminLogic.sol
- src/rollup/RollupEventInbox.sol
- src/rollup/RollupLib.sol
- test/contract/arbRollup.spec.ts
* adds chain config string to init message data
* adds chain config string to rollup config
* adds `setChainConfig` method to ArbOwner interface
> add serialized chain config to init message data

- src/rollup/RollupEventInbox.sol
Points into https://github.com/OffchainLabs/nitro-contracts/pull/26 because it uses the ArbitrumChecker
> Include the current data cost in the init message

- src/osp/OneStepProverHostIo.sol
As a proof-of-concept for adding more preimage types to the one step proof, this adds SHA256 support.
> Add sha256 preimage support

- src/osp/OneStepProverHostIo.sol
Reverts OffchainLabs/nitro-contracts#50 to unblock [release](https://github.com/OffchainLabs/nitro-contracts/pull/57) before further review
> revert: "Add sha256 preimage support"

- src/rollup/RollupCreator.sol
picked from https://github.com/OffchainLabs/bold/pull/447
> fix: additional params to rollup creator salt

- hardhat.config.ts
> Hardhat config update

- scripts/deployment.ts
Do verification by default  (unless DISABLE_VERIFICATION is used)
> Fix verification of contracts after deployment

- foundry.toml
- test/contract/arbRollup.spec.ts
- test/foundry/SequencerInbox.t.sol
- test/foundry/util/TestUtil.sol
Will add more in additional PRs
> Added some basic seq inbox foundry tests

- deploy/SequencerInboxStubCreator.js
Points into https://github.com/OffchainLabs/nitro-contracts/pull/119 to give nitro a good pin to use
> Fix SequencerInboxStubCreator

- src/precompiles/ArbOwnerPublic.sol
Points into https://github.com/OffchainLabs/nitro-contracts/pull/125
> Add ArbOS precompile method to get scheduled upgrade

- deploy/SequencerInboxStubCreator.js
- src/bridge/SequencerInbox.sol
- src/precompiles/ArbGasInfo.sol
https://github.com/OffchainLabs/nitro/pull/2109
> Add missing getters for L1 pricing parameters to ArbGasInfo

- .github/workflows/audit-ci.yml
- audit-ci.jsonc
- package.json
- yarn.lock
This PR allows the repo to run `yarn audit-ci` on ci
> ci: add audit-ci

- scripts/deploymentUtils.ts
Don't set reader4844 if running on Arbitrum chain
> Set proper params for SequencerInbox

- scripts/rollupCreation.ts
This fixes the testnode issue where posting assertions fails due to validator not being whitelisted
> Properly calculate and configure validator addresses

- test/foundry/ERC20Outbox.t.sol
- test/foundry/Outbox.t.sol
https://github.com/OffchainLabs/bold/pull/662
> test: improve outbox tests

- package.json
- scripts/deploymentUtils.ts
- scripts/local-deployment/deployCacheManager.ts
- scripts/local-deployment/deployCreatorAndCreateRollup.ts
Add function in utilities that deploys cache managers and enables it in precompile
Add script and yarn action to enable calling it from testnode
> Add script to deploy cache manager in testnode

- .github/workflows/contract-tests.yml
- audit-ci.jsonc
- package.json
> ci: upload 4bytes

- audit-ci.jsonc
- src/rollup/RollupCreator.sol
Make it up to date
Also update audit-ci.jsonc
> Update RollupCreator natspec

- hardhat.config.ts
- package.json
- scripts/createEthRollup.ts
- scripts/deployment.ts
- scripts/deploymentUtils.ts
- scripts/rollupCreation.ts
- src/mocks/BridgeUnproxied.sol
- yarn.lock
> chore: verification improvements

- src/express-lane-auction/Balance.sol
- test/foundry/ExpressLaneAuction.t.sol
- test/foundry/ExpressLaneBalance.t.sol
* Typo fixes
* Allow auction to resolve for 0 tokens
> Express lane auction 0 bid win

- .github/workflows/contract-tests.yml
- audit-ci.jsonc
- test/contract/toolkit4844.ts
> ci: remove 4844 testnode ref

- test/e2e/orbitChain.ts
cherrypicked a fix from https://github.com/OffchainLabs/nitro-contracts/pull/252
> fix: orbit e2e

- LICENSE.md
- README.md
Mirrors https://github.com/OffchainLabs/nitro/pull/2813
> Update Arbitrum Expansion Program links

- src/mocks/SelfDestruct.sol
Related to NIT-3109
Pulled in https://github.com/OffchainLabs/nitro/pull/3062
> SelfDestruct helper contracts for unit testing SelfDestruct
